Javascript -> Módulo 4 -> Tópico 1
luanarahal/training-software-engineer pull request #14
Opened 2023-12-21 17:48 UTC by luanarahal

2023-12-21 19:20 UTC, antoniomatiolijr requested changes

2023-12-21 19:20 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-2.js
> +        throw new Error("Não aceitamos fazer divisão com número negativo");
Tira a pessoalidade da msg.

"Não é possível realizar divisão com números negativos."

2023-12-22 14:14 UTC, antoniomatiolijr requested changes

2023-12-22 14:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-2.js
> +    if (number1 < 0 || number2 < 0) {
`<=` pq o zero tb da Infinity ou vai resultar em 0 ou seja inutil

2023-12-22 14:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-3.js
> +    return error;
```javascript
return "E-mail cadastro com sucesso!"
```

2023-12-22 14:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-3.js
> +    if (emailPattern.test(email)) {
if (!emailPattern.test(email)) {

2023-12-22 14:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-3.js
> +    return error;
Essa variável error não existe

2023-12-22 14:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-3.js
> +        return "E-mail cadastrado com sucesso!";
```javascript
throw new Error("E-mail inserido é inválido!");
```

2023-12-22 14:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-3.js
> +    console.error("Formato de e-mail inválido!")
Como você criou com o `throw` dentro da função a mensagem que eu sugeri já o suficiente ou seja

`console.error(error.message)`

2023-12-22 14:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-6.js
> +}
se criou uma de fechar conexão, tem que criar uma de abrir

2023-12-22 14:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-6.js
> +    if(age < 0) {
!age || age < 0

2023-12-22 14:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-6.js
> +    if(!age) {
mata esse

2023-12-22 14:27 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-6.js
> +    if(age < 0) {
aiiii que ódio eu tinha feito assim kkkk mas ai pensei em deixar mensagens diferentes

2023-12-22 17:23 UTC, antoniomatiolijr requested changes

2023-12-22 17:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-10.js
> +    console.log(`O range da idade digitado é de: ${rangeAgeStudents(age)}`);
ta errado.

Todo mundo que chamar sua função vai ter que implementar essa regra?

2023-12-22 17:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-10.js
> +    console.log(`O range da idade digitado é de: ${rangeAgeStudents(age)}`);
é a mesma coisa do `ex-3.js`

2023-12-22 17:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-8.js
> +try {
mesmo erro

2023-12-22 17:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-9.js
> +try {
mesmo erro

2023-12-23 02:21 UTC, antoniomatiolijr requested changes

2023-12-23 02:21 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-8.js
> +    if (typeof monthName !== 'string' || !monthName || !monthNames.includes(monthName)) {
Coloca no começo da função para não alocar o array aleatoriamente

2023-12-24 14:12 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-8.js
> +    if (typeof monthName !== 'string' || !monthName || !monthNames.includes(monthName)) {
verdade esqueci disso

2023-12-24 17:43 UTC, antoniomatiolijr reviewed
só falta o 5

2023-12-25 03:43 UTC, antoniomatiolijr requested changes

2023-12-25 03:43 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-5.js
> +        console.error(`O tipo do erro precisa ser log ou error.`);
Aqui teria que ser throw lembra

2023-12-25 03:43 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-5.js
> +    if (type === "log") {
Muda pra info, depois explico pq 


type === "info"

2023-12-25 03:43 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-5.js
> +const logErrorInformation = (type, message, details) => {
details deveria ser um objeto qualquer

2023-12-26 12:22 UTC, antoniomatiolijr requested changes

2023-12-26 12:22 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-5.js
> +        throw new Error(`${type} -> ${message} -> ` + JSON.stringify(details));
aqui não é throw rs pq é foco dessa função fazer o `console.error`

2023-12-26 12:22 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-5.js
> +        throw new Error(`O tipo do erro precisa ser log ou error.`);
aqui sim é um `throw` pq a função seria inutil

2023-12-26 14:44 UTC, antoniomatiolijr requested changes

2023-12-26 14:44 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-5.js
> +const logErrorInformation = (type, message, details) => {
`const emitLog`

2023-12-26 14:50 UTC, antoniomatiolijr approved these changes

2023-12-26 14:51 UTC, merged