Javascript -> Módulo 5 -> Tópico 2
luanarahal/training-software-engineer pull request #16
Opened 2024-01-03 18:20 UTC by luanarahal

2024-01-13 18:48 UTC, antoniomatiolijr requested changes

2024-01-13 18:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-2.js
> +        }
vc não precisa do else, pode usar aquele conceito de retorno antecipado só mantendo um if, e ai vc faz if id !== 1 vc da o reject caso esteja certo vc resolve com o sucesso.

2024-01-13 18:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-4.js
> +    console.log(randomNumber);
e esse console log sobrando kkk

2024-01-13 18:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-5.js
> +    .then(data => console.log(data));
fica mais readable vc por os thens em cadeia, não precisa dessa função featchData

2024-01-13 18:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-6.js
> +featchData('https://jsonplaceholder.typicode.com/todos/1')
igual anterior

2024-01-13 18:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-9.js
> +            setTimeout(() => resolve("Mensagem retornada com sucesso!"), 5000);
só para vc testar muda para 2segundos, vc vai ver que a implementação está errada

2024-01-15 15:44 UTC, antoniomatiolijr requested changes

2024-01-15 15:44 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-10.js
> +            .catch(err => console.error(err));
pode tirar essa parte de dentro da função, ta bem complicado de entender com muita coisa

2024-01-15 15:44 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-4.js
> +    let randomNumber = Math.floor(Math.random() * (max - min * 1) + min);
vc pode criar uma função que gera esse numero random e só chamar aqui

2024-01-15 15:44 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-9.js
> +            .catch(err => reject(err));
mandou bem

2024-01-15 19:38 UTC, antoniomatiolijr requested changes

2024-01-15 19:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-10.js
> +    let max = 10;
concorda comigo que isso deveria ser parâmetros da sua função, do tipo, a pessoa pode escolher o range dos números randomicos?

2024-01-15 19:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-4.js
> +const generateRandomNumber = () => {
carambaaaa vc tem uma função sendo reutilizada em dois lugares? e o que acha de usar um utils de numbers?

2024-01-15 20:19 UTC, antoniomatiolijr requested changes

2024-01-15 20:19 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-10.js
> +    const randomNumber = Math.floor(generateRandomNumber(0, 10));
Math.floor deve ser da função, a pergunta só é se vc quer uma função que sempre retorne inteiros ou não

2024-01-15 20:19 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/utils.js
> +    return (Math.random() * (max - min) + min).toFixed(2);
pq esse toFixed?

2024-01-15 20:36 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-10.js
> +    const randomNumber = Math.floor(generateRandomNumber(0, 10));
é porque no exercício 10 eu quero que retorne um número inteiro de 1 a 10, e no exercício 4 eu quero que retorne um número entre 0 a 1 e com duas casas decimais

2024-01-15 20:43 UTC, antoniomatiolijr requested changes

2024-01-15 20:43 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-10.js
> +    const randomNumber = Math.floor(generateRandomNumber(0, 10));
e como vc faz uma função dinâmica que faz isso?

2024-01-16 01:51 UTC, antoniomatiolijr requested changes

2024-01-16 01:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/utils.js
> +    if (precision) {
Caraaamba e se eu passar na função (0, 10, "Caraaaamba") me conta o que rola?

2024-01-16 02:03 UTC, antoniomatiolijr approved these changes

2024-01-16 02:03 UTC, merged