Javascript -> Módulo 6 -> Tópico 2
luanarahal/training-software-engineer pull request #18
Opened 2024-01-25 20:50 UTC by luanarahal

2024-01-26 04:35 UTC, antoniomatiolijr requested changes
faz com async/await

2024-01-26 04:37 UTC, antoniomatiolijr reviewed
Seção 5: Consumindo uma API na Prática lembra de fazer a seção 5 da aula onde cada um dos exemplos é um exercício separado

2024-01-30 19:10 UTC, antoniomatiolijr requested changes

2024-01-30 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +const url = 'http://localhost:3000/client';
```typescript

const CLIENT_SERVICE_URL = 'http://localhost:3000/client';

```

2024-01-30 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-2.js
> +const apiKey = 'c584d3029130c723e9e022f7b70f7058';
API_KEY

2024-01-30 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-2.js
> +const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${apiKey}&units=metric`;
OPEN_WEATHER_URL

2024-01-30 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-2.js
> +const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${apiKey}&units=metric`;
vc Pode criar uma função que aceita a cidade e devolve a URL montada com a cidade

2024-01-30 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-2.js
> +        console.log(`Temperatura em ${city}: ${response.main.temp} °C`);
nunca acesse a variável global

2024-01-30 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +        const data = await fetch(`${url}/${id}`, {
```typescript

{
            method: 'PATCH',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(dados)
        }
        
```

2024-01-30 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +        const data = await fetch(`${url}/${id}`, {
Essa parte se repete algumas vezes, consegue criar uma função que gera?

2024-01-30 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-5.js
> +const url = `https://api.themoviedb.org/3/search/movie?api_key=${apiKey}&query=${query}`;
aqui mesma coisa

2024-01-30 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-5.js
> +const query = 'Inception';
gostei do filme

2024-02-01 13:14 UTC, antoniomatiolijr requested changes

2024-02-01 13:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-2.js
> +}
makeOpenWeatherURL

2024-02-01 13:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-2.js
> +const getURL = async (city) => {
essa é uma função async?

2024-02-01 13:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +}
makeRequest(httpMethod, contentType, bodyData);

detalhe tem que checar se tem bodyData, para colocar body no objeto, pois ele pode ser nulo

2024-02-01 13:14 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +const getMethod = async (method, dados) => {
essa é uma função async?

2024-02-05 12:54 UTC, antoniomatiolijr requested changes

2024-02-05 12:54 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +}
Um jeito um pouquinho mais simples de entender. Também coloquei um valor default para `contentType` dessa forma não preciso fazer um if especifico pq a maioria das vezes vai ser `application/json`
```typescript
const makeRequest = (httpMethod, contentType= 'application/json', bodyData) => {
    const requestConfig = {
        method: httpMethod,
        'Content-Type': contentType
    };
    
    if (bodyData) {
        requestConfig.body = JSON.stringify(bodyData);
    }

    return requestConfig;
}
```

2024-02-05 12:54 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +}
e pode ser colocado em um utils da vida

2024-02-05 12:54 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +        const response = await data.text();
pq text?

2024-02-06 22:23 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +}
nossa ficou muitoooo melhor kkk

2024-02-06 22:28 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +        const response = await data.text();
eu não sei se eu to fazendo algo errado, mas quando eu tento com json, retorna isso:

`SyntaxError: Unexpected token 'c', "client id:"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4747:19)
    at successSteps (node:internal/deps/undici/undici:4718:27)
    at fullyReadBody (node:internal/deps/undici/undici:1433:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:4727:7)
    at async putClient (file:///Users/luana/Documents/training-software-engineer/associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js:50:26)`

esse 'client id:...' é o retorno da API.
Acho que pelo fato da API retornar 'client id: 37060ac6-e176-49e3-80df-9b76bdc54e1e has been updated' e não retornar o json em si quando fazemos update e delete, ai da esse erro se não for text

2024-02-07 12:23 UTC, antoniomatiolijr requested changes

2024-02-07 12:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +// getAllClients(CLIENT_SERVICE_URL)
👀

2024-02-07 12:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +// })
👀

2024-02-07 12:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +const putClient = async (url, id, dados) => {
dados?

2024-02-07 12:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-4.js
> +const OPEN_POKEMON_URL = getPokemonName("pikachu");
vc não ta pegando só o nome do pokemon, esse nome não representa o que a função faz

2024-02-07 12:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-3.js
> +const GITHUB_REPOS_URL = getGithubName("luanarahal");
mesma coisa do pokemon o que vc ta fazendo é montando a URL somente

2024-02-07 12:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-5.js
> +const getMovieURL = (name, key) => {
mesma coisa

2024-02-07 14:40 UTC, antoniomatiolijr requested changes

2024-02-07 14:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-3.js
> +const GITHUB_REPOS_URL = getGithubName("luanarahal");
esqueceu?

2024-02-08 03:24 UTC, antoniomatiolijr approved these changes

2024-02-08 03:24 UTC, merged