Javascript -> Módulo 7 -> Tópico 1
luanarahal/training-software-engineer pull request #20
Opened 2024-02-09 20:31 UTC by luanarahal

2024-02-10 03:25 UTC, antoniomatiolijr requested changes
Não entendi de onde você tirou esses

2024-02-10 03:25 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/ex-1.html
> +</html>
Falta adicionar um enter

2024-02-10 03:25 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/ex-1.js
> +for (let link of links) {
const link

2024-02-10 03:25 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/ex-1.js
> +for (let item of itens) {
const item

2024-02-10 03:25 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/ex-1.js
> +for (let emp of empha) {
const emp

2024-02-10 03:25 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/ex-1.js
> +var span = document.getElementsByTagName("span");
Var?

2024-02-10 03:25 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/ex-1.js
> +var empha = document.getElementsByClassName("emphasis");
Var?

2024-02-11 19:13 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/ex-1.html
> +</html>
eu tinha dado, mas quando salvo o arquivo ele tira o enter 🤡

2024-02-12 02:58 UTC, antoniomatiolijr requested changes

2024-02-12 02:58 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const paragraph = document.getElementsByTagName("p");
Eh no plural

2024-02-12 02:58 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const item = document.querySelector(".item");
Plural pois pode retornar mais de um item logo, representando uma lista

2024-02-12 02:58 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +console.log(item);
Tira o console log

2024-02-12 02:58 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const link = document.querySelectorAll("a.link");
No plural pois novamente pode retornar uma lista de links

2024-02-12 02:58 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const item2 = document.querySelectorAll(".item");
Mesma coisa de plural

2024-02-12 02:58 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const empha = document.getElementsByClassName("emphasis");
Não sei se esse é o melhor nome, mas só lembrando que deve estar no plural

2024-02-12 02:58 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +    console.log(emp);
Remover console log

2024-02-12 02:58 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +console.log(empha);
Remover console log

2024-02-12 02:58 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const span = document.getElementsByTagName("span");
Plural

2024-02-14 12:48 UTC, antoniomatiolijr requested changes

2024-02-14 12:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/Luana.jpeg
imagens devem ter o nome minusculo

2024-02-14 12:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +for (let paragraph of paragraphs) {
const

2024-02-14 12:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const highlights = document.getElementsByClassName("emphasis")[0];
highlight aqui vc pegou a posição [0]

2024-02-14 12:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +for (let link of links) {
`const link` n vai mudar nada no link, logo pode usar const para economizar memoria

2024-02-14 12:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +console.log(empha);
o console log continua aqui

2024-02-14 12:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +for (let period of periods) {
const

2024-02-14 12:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +for (let emphase of highlights2) {
const

2024-02-14 12:48 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +for (let item of items2) {
const

2024-02-16 00:38 UTC, antoniomatiolijr requested changes

2024-02-16 00:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/Luana.jpeg
imagens devem ser minusculas

2024-02-16 00:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +items.textContent = "Pode discordar, mas é a realidade!";
e se voltar mais de um?

2024-02-16 01:41 UTC, antoniomatiolijr requested changes

2024-02-16 01:41 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/Luana.jpeg
nome do arquivo deve ser minusculo em imagens

2024-02-16 12:28 UTC, antoniomatiolijr approved these changes

2024-02-16 12:28 UTC, merged