Javascript -> Módulo 7 -> Tópico 2
luanarahal/training-software-engineer pull request #21
Opened 2024-02-11 23:06 UTC by luanarahal

2024-02-14 13:00 UTC, antoniomatiolijr requested changes

2024-02-14 13:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-1.js
> +document.getElementById("buttonChangeText").addEventListener('click', function () {
Aqui você pode usar arrowFunction

2024-02-14 13:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-1.js
> +    const text = document.getElementById("paragraph");
Eh um texto ou um parágrafo?

2024-02-14 13:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-2.js
> +let state = false;
remover

2024-02-14 13:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-2.js
> +    state = !state;
remover

2024-02-14 13:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/index.html
> +    <div id="toggleDiv" style="width: 100px; height: 100px; background-color: yellow;">Div
```html
<div id="toggleDiv" style="display:block; width: 100px; height: 100px; background-color: yellow;">Div
        Ocultável</div>
```

2024-02-14 13:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-2.js
> +    }
```javascript
const toggleDivDisplay = toggle.style.display;

if (toggleDivDisplay === 'block') {
        toggle.style.display = 'none';
} else {
        toggle.style.display = 'block';
}
```

2024-02-14 13:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-3.js
> +}
Assim a função fica dinamica a qualquer elemento

```javascript

const changeBackgroundColor = (element) => {
    const color = generateColor();
    element.style.backgroundColor = color;
}
```

2024-02-14 13:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-3.js
> +document.getElementById("changeBackgroundColor").addEventListener('click', changeBackgroundColor);
```javascript
const changeBodyBackgroundColor = changeBackgroundColor(document.body)
document.getElementById("changeBackgroundColor").addEventListener('click', changeBodyBackgroundColor);
```

2024-02-14 13:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/index.html
> +        <p id="errorText" style="color: red;"></p>
normalmente usamos span para esses casos, que é um tipo de texto sem semântica. Qualquer leitor de tela ao ler um `p` vai entender como um paragrafo logo vai dar uma certa importância ao texto.

2024-02-14 13:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/index.html
> +        <p id="errorText" style="color: red;"></p>
Outra coisa mesmo se não tiver erro o p sempre aparece?

2024-02-14 13:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-4.js
> +    }
vc está usando o mesmo campo de erro para mostrar uma mensagem de sucesso?

2024-02-14 13:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-4.js
> +const verifyEmail = () => {
aqui vc não está verificando o email, vc ta verificando se o campo está preenchido. Atualizar o nome da função para algo como `verifyInput` ou adicionar um regex que de fato verifica o email.

2024-02-14 23:49 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-2.js
> +    }
nossa muito melhor kkk

2024-02-16 00:37 UTC, antoniomatiolijr requested changes

2024-02-16 00:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-1.js
> +    paragraph.textContent = "Texto alterado!";
pq isso é ruim, pq se vc precisar usar o paragrafo em outro canto vc não consegue.

Basicamente deixa só a linha 3 dentro. E o getElementById fora.

2024-02-16 00:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-4.js
> +const checkEmptyField = () => {
passa o html como parametro

2024-02-16 00:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-4.js
> +        error.innerHTML = "Digite um e-mail!";
passa a msg como parametro da função tb

2024-02-16 00:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-6.js
> +    console.log(number);
pode tirar esse console.log

2024-02-16 00:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-6.js
> +    const numberElement = document.getElementById("clickCounter");
passa esse cara como parametro pq ai vc pode reutilizar essa função em outros lugares

2024-02-16 00:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-7.js
> +    document.getElementById("hoverText").style.color = "blue";
Esse vc passa como parametro: `document.getElementById("hoverText")` e a cor tb. assim fica dinamico

2024-02-16 00:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-7.js
> +    document.getElementById("hoverText").style.color = '';
igual anterior

2024-02-16 00:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-8.js
> +    const animateDiv = document.getElementById("animateDiv");
passa como parametro

2024-02-16 01:40 UTC, antoniomatiolijr requested changes

2024-02-16 01:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-4.js
> +        return errorMessage.innerHTML = "Digite um e-mail!";
é return?

2024-02-16 01:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-4.js
> +    const errorMessage = document.getElementById(error);
esse vc pode deixar dentro, pois faz parte do contexto da função

Logo     const errorMessage = document.getElementById('error');

2024-02-16 01:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-4.js
> +    const emailBox = document.getElementById(emailInput);
remover e passar direto o inputHTML

2024-02-16 01:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-4.js
> +    checkEmptyField("emailInput", "error")
const emaiInputHTML = document.getElementById('emailInput');
checkEmptyField(emaiInputHTML,  "Mensagem de erro aqui")

2024-02-16 01:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-6.js
> +    numberElement.textContent = number;
da para simplificar?

2024-02-16 01:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-6.js
> +    const numberElement = document.getElementById(clickCounter);
passa o domNode para a função como sugeri no outro exercício.

const clickCounterNode = document.getElementById(clickCounter);


const countNumber = (clickCounterNode)

2024-02-16 01:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-7.js
> +    document.getElementById(hoverText).style.color = color;
mesma coisa

2024-02-16 01:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-7.js
> +}
mesma coisa

2024-02-16 01:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-8.js
> +    const div = document.getElementById(animateDiv);
mesma coisa

2024-02-16 01:59 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-4.js
> +}
yessssss!!!!! é isso

2024-02-16 02:01 UTC, antoniomatiolijr requested changes

2024-02-16 02:01 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-6.js
> +    let number = parseInt(clickCounterNode.textContent) + 1;
const number

Vc não está mudando ela, na próxima interação vai ser uma nova variável

2024-02-16 02:01 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-2/ex-8.js
> +const moveDiv = (animateDiv) => {
const moveElement = (element)

2024-02-16 02:09 UTC, antoniomatiolijr approved these changes

2024-02-16 02:09 UTC, merged