feat: simple sum
luanarahal/training-software-engineer pull request #3
Opened 2023-09-04 18:10 UTC by luanarahal

2023-09-06 12:40 UTC, antoniomatiolijr requested changes

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-1.py
> +sum = n1 + n2
o ideal não é usar sum, pq existe uma função de `sum()` e assim vc mata a existência dela kkk

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-10.py
> +print(int(n))
sempre faça a conversão fora do print, o máximo que conseguir tirar operações do print melhor

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-11.py
> +print(name + " " + surname)
aqui https://docs.python.org/3/tutorial/inputoutput.html tem uma documentação de como fazer sem o `+`

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-12.py
> +print(len(name))
mesma coisa de em cima, manter fora do print outras operações

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-13.py
> +print(name[:3])
Aqui tb

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-14.py
> +print(name)
o problema de vc guardar na mesma variavel é que vc altera ela e nunca mais volta ao estado anterior, nesses casos é sempre melhor criar outras variáveis

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-15.py
> +name = name.find("n")
sempre crie outra variável

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-20.py
> +print(float(n))
aqui tb

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-21.py
> +print(int(n))
aqui tb

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-23.py
> +print("x =", x)
aqui da para usar `format` tb

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-3.py
> +print(int(div))
aqui tb

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-4.py
> +print(int(rest_of_division))
aqui tb

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-8.py
> +print(round(n))
aqui tb

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-7.py
> +print(float(sum))
aqui tb

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-6.py
> +print(float(sum))
aqui tb

2023-09-06 12:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-5.py
> +print(int(exponential))
aqui tb

2023-09-28 14:11 UTC, antoniomatiolijr requested changes

2023-09-28 14:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-11.py
> +print(f'{name} {surname}')
ta ok a unica coisa que eu faria era tirar de dentro do print algo como.
```python
full_name =  f"{name}{surname}"
print(full_name)
```

2023-09-28 14:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-12.py
> +name = len("Luana")
```python
name = "Luana"
name_length = len(name)

print(name_length)
```

2023-09-28 14:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-14.py
> +name2 = name.upper()
melhora o nome das variaveis

2023-09-28 14:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-26.py
> +days = date1 - date2
difference = date1 - date2

2023-09-28 14:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-26.py
> +print(days)
print(difference.days)

Tem uma propriedade que só te retorna os dias

2023-09-28 14:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-27.py
> +date_final = (date + days).strftime('%d/%m/%Y %H:%M:%S')
final_date

2023-09-28 14:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-27.py
> +print("Depois de 10 dias, a partir de hoje, a data sera:", date_final)
days_to_add = 10
days = timedelta(days_to_add)

print(f"Depois de {days_to_add} dias, a partir de hoje, a data sera:", date_final)

Só para não ficarmos dependendo de repetir o número

2023-09-28 14:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-3.py
> +print(div)
```python
# Declaração de duas variáveis inteiras
num1 = 10
num2 = 3

# Divisão inteira
resultado = num1 // num2
```

Neste exemplo, 10 // 3 retorna 3, pois 10 dividido por 3 é igual a 3 com um resto de 1. O operador // descarta o resto e retorna apenas o valor inteiro do quociente.

2023-09-28 14:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-6.py
> +sum = float(n1 + n2)
não precisa desse `float` e usa um outro nome para `sum` pois é um nome reservado

2023-09-28 14:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-6.py
> +sum = float(n1 + n2)
não precisa desse `float` e usa um outro nome para `sum` pois é um nome reservado

2023-09-28 14:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-7.py
> +sum = float(n1 / n2)
igual o exercicio anterior

2023-09-28 14:47 UTC, luanarahal commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-26.py
> +print(days)
ameeeeeeeeei

2023-09-28 23:36 UTC, antoniomatiolijr approved these changes

2023-10-09 15:02 UTC, adrianopratesr approved these changes

2023-10-09 15:02 UTC, merged