Feat/se1 fc1 js modulo 1
luanarahal/training-software-engineer pull request #4
Opened 2023-09-22 15:27 UTC by luanarahal

2023-10-09 05:05 UTC, antoniomatiolijr requested changes

2023-10-09 05:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-1/ex-13.js
> +    fullString = fullString + " " + name;
fullString += " " + name;

2023-10-09 05:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-1/ex-3.js
> +        break;
lembre-se de sempre adicionar um default para um switch, pois caso não bata com nenhum dos anteriores ele vai para o default

2023-10-09 05:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-1/ex-7.js
> +}
```typescript
const string = "Luana"
let invertedString = "";

for (let char of string) {
invertedString = char + invertedString
}

console.log(invertedString)
```

O segredo ta aqui `invertedString = char + invertedString`, ao colocar invertedString depois, vc garante que a atual seja sempre colocada a esquerda ou seja , fazendo um teste de mesa:

1. 
invertedString = ""
char = "L"


char + invertedString => "L" + ""
invertedString = "L"

2. 
invertedString = "L"
char = "u"

char + invertedString => "u" + "L"
invertedString = "uL"

3. 
invertedString = "uL"
char = "a"

char + invertedString => "a" + "uL"
invertedString = "auL"


4. 
invertedString = "auL"
char = "n"

char + invertedString => "n" + "auL"
invertedString = "nauL"

5. 
invertedString = "nauL"
char = "a"

char + invertedString => "a" + "nauL"
invertedString = "anauL"

2023-10-09 05:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-1/ex-8.js
> +let qtdProperties = 0;
qtd? como é em ingles?

2023-10-09 05:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-12.py
> +print(len(name))
armazena em uma variável fora do print

2023-10-09 05:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-13.py
> +print(name[:3])
igual o anterior

2023-10-09 05:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-15.py
> +name = name.find("n")
cria uma variável nova, vc está mudando a anterior assim, isso em um sistema real pode causar um `side effect` não controlado

2023-10-09 05:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-6.py
> +sum = float(n1 + n2)
result = n1 + n2

2023-10-09 05:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-6.py
> +print(sum)
sum é uma função em python, ao fazer isso vc está sobrescrevendo ela para sua conta, basicamente vc não pode usar mais essa função no seu código ao fazer isso

2023-10-09 05:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/phyton/modulo-1/topico-2/ex-7.py
> +sum = float(n1 / n2)
igual anterior

2023-10-09 15:30 UTC, antoniomatiolijr approved these changes

2023-10-16 15:18 UTC, adrianopratesr approved these changes

2023-10-16 15:18 UTC, merged