Feat/se1 fc1 js modulo 2
luanarahal/training-software-engineer pull request #5
Opened 2023-10-16 14:43 UTC by luanarahal

2023-10-17 00:23 UTC, antoniomatiolijr requested changes

2023-10-17 00:23 UTC, antoniomatiolijr commented on associate-software-engineer/.gitignore
> +aula.js
enter no final

2023-10-17 00:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-12.js
> +const concatenateStrings = words.reduce((phrase, word) => phrase + word);
Está faltando inicializar depois do phrase + word, "");

2023-10-17 00:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-19.js
> +export const estudantes = [
Cria um arquivo chamado mock e exporta como vc fez, sempre usamos um arquivo chamado mock nesses casos

2023-10-17 00:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-19.js
> +const names = estudantes.map(name => name.nome);
name é um nome ruim, usa student e muda de estudantes para students

2023-10-17 00:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-20.js
> +const minorOf21 = estudantes.filter(minor => minor.idade < 21);
Troca minor por student, lembre se que cada minor é um estudante pois está iterando no array

2023-10-17 00:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-21.js
> +const age20 = estudantes.find(age => age.idade === 20);
studentWith20

2023-10-17 00:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-22.js
> +const over19YearsOld = estudantes.every(age => age.idade >= 19);
Em inglês

2023-10-17 00:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-24.js
> +const averageAgeStudents = estudantes.reduce((average, age) =>  average + age.idade, 0)/estudantes.length;
Sempre quebra em duas expressões

2023-10-17 00:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-25.js
> +const nameStartingWithA = estudantes.filter(name => name.nome[0] === 'A');
Name USA Uma variável melhor

2023-10-17 00:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-26.js
> +    if (name1.nome > name2.nome) {
Da pra melhorar bastante esse código faz um teste de mesa e vai entender como

2023-10-17 00:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-7.js
> +const double = numbers.map(item => item * 2);
Double da a sensação que é um valor só e não uma lista de valores duplicados

2023-10-24 13:13 UTC, antoniomatiolijr requested changes

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-15.js
> +console.log(numbers.some(item => item / item !== 0));
item < 0

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-15.js
> +console.log(numbers.some(item => item / item !== 0));
e pq colocou direto no console log?

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-16.js
> +console.log(numbers.every(item => item > 0));
meow

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-20.js
> +const minorOf21 = students.filter(student => student.idade < 21);
studentsUnder21

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-22.js
> +const over19YearsOld = students.every(student => student.idade >= 19);
studentsOver19

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-23.js
> +const ageEqualTo21 = students.some(student => student.idade === 21);
studentsWith21

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-24.js
> +const addingUpTheAges = students.reduce((average, age) => average + age.idade, 0);
alguma coisa que seja soma, acumulo quantidade

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-24.js
> +const averageAgeStudents = addingUpTheAges/students.length;
está faltando espaçamento

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-25.js
> +const nameStartingWithA = students.filter(student => student.nome[0] === 'A');
studentsNameStartingWithA

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-26.js
> +});
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-27.js
> +    }
da para reduzir para uma linha

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-29.js
> +});
eu só trocaria os nomes student 1 na verdade é `oldestStudent` (pois vc vai guardar o mais velho) e o student2 na verdade é student (pq é o student atual da iteração)

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-30.js
> +const namesWithMoreThreeCharacters =
studentsNameWithMoreThan3Chars

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-31.js
> +const howManyStudentsOverTwentyTearsOld =
studentsOver20

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-7.js
> +const duplicateValues = numbers.map(item => item * 2);
duplicatedValues

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-33.js
> +}
return accumulator + student.idade;

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-33.js
> +const averageAge = sumOfAges/((addingUpAges.length) + 1);
está faltando espaços e pq o +1?

2023-10-24 13:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-32.js
> +console.log(students.some(thereAreStudentsOfTheSameAge));
```typescript

const checkStudentsWithSameAge = (currentStudent, index, students) => {
    return students.filter(student => student.idade === currentStudent.idade).length > 1;
}

console.log(students.some(checkStudentsWithSameAge));

```

2023-10-30 17:41 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-32.js
> +console.log(students.some(thereAreStudentsOfTheSameAge));
não entendi essa parte ".length > 1"

2023-10-30 17:41 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-33.js
> +const averageAge = sumOfAges/((addingUpAges.length) + 1);
porque o array começa com 0, ai precisa somar 1 pra dar certo a média

2023-10-31 15:38 UTC, antoniomatiolijr requested changes

2023-10-31 15:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-16.js
> +const checkIfAllNumbersArePositive = numbers.every(item => item > 0)
Isso é nome de função sempre que tiver um verbo é função.

O certo seria positiveNumbers

2023-10-31 15:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-23.js
> +const studentsWith21 = students.some(student => student.idade === 21);
thereAreStudentsWith21

2023-10-31 15:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-24.js
> +const averageAgeStudents = sumOfAges/students.length;
Tá faltando espaço

2023-10-31 15:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-26.js
> +const alphabeticalOrder = students.sort((student1, student2) => student1.nome.localeCompare(student2.nome));
precisa melhorar a formatação do código.

E lembra o nome da variável representa o que tem nela e nela tem agora `sortedStudentsByName `

2023-10-31 15:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-26.js
> +const alphabeticalOrder = students.sort((student1, student2) => student1.nome.localeCompare(student2.nome));
studentsSortedByAgeDescending or studentsOrderedByDescendingAge

Tem que dar contexto eu não consigo entender nada só com alphabeticalOrder

2023-10-31 15:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-27.js
> +const orderByAgeDescending = students.sort((student1, student2) => student2.idade.toString().localeCompare(student1.idade.toString()) );
Igual anterior e com a formatação

2023-10-31 15:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-32.js
> +console.log(students.some(checkStudentsWithSameAge));
faltando enter

2023-10-31 15:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-32.js
> +console.log(students.some(checkStudentsWithSameAge));
pq não armazenou em uma variável?

2023-10-31 15:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-33.js
> +const averageAge = sumOfAges/((addingUpAges.length) + 1);
Aqui está errado e sim

`const studentsStartingNameWithA = students.filter(student => student.nome[0] === 'A')`

`const averageAge = sumOfAges / studentsStartingNameWithA.length;`

2023-10-31 15:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-33.js
> +console.log(students.filter(student => student.nome[0] === 'A'))
E NAOOO FAZ NO CONSOLE LOG A FUNCAAAO AAAAAAA

2023-10-31 16:06 UTC, antoniomatiolijr requested changes

2023-10-31 16:06 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-34.js
> +console.log(filteringTheYoungestAboveTwentyYearsOld);
```javascript
const findYoungest = (acc, student) => {
  return (acc.idade < student.idade) ? acc : student;
}

const studentsAbove20 = students.filter(student => student.idade > 20);

if (studentsAbove20.length > 0) {
  const youngestStudentAbove20 = studentsAbove20.reduce(findYoungest);
  console.log(`O estudante mais jovem com idade acima de 20 é ${youngestStudentAbove20.nome} com ${youngestStudentAbove20.idade} anos.`);
} else {
  console.log("Não há estudantes com idade acima de 20.");
}



```

2023-10-31 16:06 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-34.js
> +console.log(filteringTheYoungestAboveTwentyYearsOld);
bem mais simples

2023-10-31 16:06 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-35.js
> +            return student1.idade.toString().localeCompare(student2.idade.toString())
return student1.idade.toString().localeCompare(student2.idade.toString())
            
 idade é um inteiro não precisa de local compare

2023-10-31 16:06 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-37.js
> +const averageAgesStudents = sumOfAges/students.length;
averageAgeFromStudents

2023-10-31 16:06 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-37.js
> +const averageAgesStudents = sumOfAges/students.length;
E está faltando formatação (está faltando espaço)

2023-10-31 16:06 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-37.js
> +const averageAgesStudents = sumOfAges/students.length;
CONFIGURA O FORMATADOR MULHER

2023-10-31 16:06 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-39.js
> +const eventos = [...Array(50)].map((_,i) => ({ nome: `Evento${i+1}`, data: new Date(2022+i, 1, 1)}));
Falta um enter

2023-10-31 16:06 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-38.js
> +    .filter(person => formattedDate(person.dataNascimento) < '01-01-1990')
.filter(person => person.dataNascimento < newDate('1990-01-01'))

2023-10-31 16:06 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-38.js
> +    .map(person => `Nome: ${person.nome} - Data de nascimento: ${formattedDate(person.dataNascimento)}`)[0];
Só guarda na variável depois checa se tem algo no array e ai sim da um console log com a pessoa mais velha ou não temos dados.

2023-10-31 16:06 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-39.js
> +const eventos = [...Array(50)].map((_,i) => ({ nome: `Evento${i+1}`, data: new Date(2022+i, 1, 1)}));
esperando o resto

2023-10-31 20:26 UTC, antoniomatiolijr requested changes

2023-10-31 20:26 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-24.js
> +const averageAgeStudents = sumOfAges/students.length;
ta faltando espaço 


sumOfAges/students.length; => sumOfAges / students.length;

2023-10-31 20:26 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-32.js
> +const checkStudentsOfTheSameAge = (students.some(studentsWithSameAge));
não precisa de parenteses em volta

2023-10-31 20:26 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-33.js
> +}
arrow function

2023-10-31 20:26 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-33.js
> +const averageAge = sumOfAges/studentsStartingNameWithA.length;
faltando espaço

2023-10-31 20:26 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-35.js
> +        }
só para ficar mais simples de ler

```javascript

if(student1.nome[0] !== student2.nome[0]) {
 return student1.nome.localeCompare(student2.nome);
}

return return student1.idade - student2.idade;




```

2023-10-31 20:26 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-35.js
> +const listStudentsAlphabetically = students
qual seria o nome da variavel correta nesse caso dado os exemplos que eu dei?

2023-10-31 20:26 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-38.js
> +if (people.length > 0) {
A lógica está errada.

agora faz olderPeople.length > 0

2023-10-31 20:26 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-39.js
> +        const year = formattedDate(event.data);
const year = event.data.getFullYear();

2023-10-31 20:26 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-38.js
> +    .map(person => `${person.nome} - Data de nascimento: ${formattedDate(person.dataNascimento)}`)[0];
Remove o [0]

2023-10-31 20:26 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-38.js
> +    console.log(`A pessoa mais velha que nasceu antes de 01-01-1990 é: ${olderPeople}`);
olderPeople[0]

2023-10-31 20:26 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-39.js
> +        accumulator[year]++;
accumulator[year] = (accumulator[year] || 0) + 1;
  
  
  para garantir que o código não quebre

2023-10-31 20:58 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-33.js
> +const averageAge = sumOfAges/((addingUpAges.length) + 1);
ah ta!!! agora deu certo

2023-10-31 20:58 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-34.js
> +console.log(filteringTheYoungestAboveTwentyYearsOld);
much better

2023-10-31 20:58 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-35.js
> +        }
much better

2023-11-01 03:37 UTC, antoniomatiolijr requested changes

2023-11-01 03:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-27.js
> +const studentsSortedByDescendingAge = students
n precisa de localCompare quando é número, qual usa nessa situação mesmo?

2023-11-01 03:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-32.js
> +const studentsWithSameAge = (currentStudent, index, students) => {
checkStudentsOfTheSameAge o nome dessa função é isso

2023-11-01 03:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-32.js
> +const checkStudentsOfTheSameAge = students.some(studentsWithSameAge);
e aqui haveStudentsWithSameAge

2023-11-01 03:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-35.js
> +const sortStudentsAlphabeticallyAndByAge = students
sortedStudentsAlphabeticallyAndByAge

2023-11-01 03:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-32.js
> +const studentsWithSameAge = (currentStudent, index, students) => {
pq uma função sempre deve ser um verbo o que ela faz?

checar estudantes com a mesma idade

2023-11-08 12:28 UTC, antoniomatiolijr requested changes

2023-11-08 12:28 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-32.js
> +const haveStudentsWithSameAge = students.some(checkStudentsOfTheSameAge );
espaço sobrando

2023-11-08 12:28 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-40.js
> +const checkNearestEvents = pessoas.map(pessoa => {
esse nome ta zuado não?

2023-11-08 12:28 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-41.js
> +        }
return year >= 2030 && year <= 2040;

2023-11-08 13:39 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-41.js
> +        }
bem mais limpo mesmo

2023-11-08 14:27 UTC, antoniomatiolijr requested changes

2023-11-08 14:27 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-32.js
> +const haveStudentsWithSameAge = students.some(checkStudentsOfTheSameAge );
`const haveStudentsWithSameAge = students.some(checkStudentsOfTheSameAge);`

2023-11-08 14:27 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-40.js
> +const checkNearestEventForEachPerson = pessoas.map(pessoa => {
ta errado ainda, isso não é uma função. função vc coloca com uma ação.

peopleWithNearestEvent

2023-11-08 14:30 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-2/ex-40.js
> +const checkNearestEventForEachPerson = pessoas.map(pessoa => {
entendi

2023-11-09 14:39 UTC, antoniomatiolijr approved these changes

2023-11-09 17:54 UTC, merged