Javascript: Módulo 2 - Tópico 2
luanarahal/training-software-engineer pull request #9
Opened 2023-11-16 01:28 UTC by luanarahal

2023-11-16 15:36 UTC, antoniomatiolijr requested changes

2023-11-16 15:36 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-10.js
> +})
só para não gerarmos um array novo da para fazer a mesma coisa com forEach

cars.forEach(car => {
    if (car.model === 'gol') {
        car.model = 'polo';
    }
})

2023-11-16 15:36 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-13.js
> +const mapa = new Map([['chave1', 'valor1'], ['chave2', 'valor2']]);
troca para exampleMap só para mantermos o padrão de nome de variáveis

2023-11-16 15:36 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-16.js
> +const mapaOriginal = new Map([['chave1', 'valor1'], ['chave2', 'valor2']]);
vamos manter em ingles

2023-11-16 15:36 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-16.js
> +const newMap = [...mapaOriginal];
const newMap = new Map(mapaOriginal);

2023-11-16 15:36 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-17.js
> +const newMap = [...mapa1] + ' ' + [...mapa2];
const newMap = new Map([...map1, ...map2])

2023-11-16 15:36 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-17.js
> +const mapa1 = new Map([['chave1', 'valor1']]);
manter em ingles

2023-11-16 15:36 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-18.js
> +const produtos = [
em ingles, mas cuidado para não dar conflito

2023-11-16 15:36 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-19.js
> +const contando = palavras.forEach(word => {
forEach é `in place` ele retorna `void` ou seja não tem retorno. Não existe pq armazenar em uma variável

2023-11-16 15:36 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-20.js
> +        }
index in keys

2023-11-16 15:36 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-20.js
> +const chaves = ['chave1', 'chave2', 'chave3'];
muda para ingles

2023-11-16 15:36 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-9.js
> +cars.map(car => car.status = 'available');
usa forEach para não gerar um novo array

2023-11-21 22:50 UTC, antoniomatiolijr requested changes

2023-11-21 22:50 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-20.js
> +const relatingKeysAndValues = arraysToMap(keys, values);
Vc está passando dois parametros porém a função só está recebendo um, mude a função para receber dois.

2023-11-21 22:50 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-20.js
> +function arraysToMap(index) {
substitui por `arrowFunction`

2023-11-21 22:50 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-20.js
> +function arraysToMap(index) {
E vc não está usando index, pq vc está recriando o index no for.

2023-11-21 22:50 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-27.js
> +for (let value of fruits) {
fruit of fruits

2023-11-21 22:50 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-28.js
> +objects.add(['caneta', 'lápis', 'livro']);
isso é um objeto? isso é um array de strings. transforme em um array de objetos

2023-11-21 22:50 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-30.js
> +const newSet = [...set1, ...set2];
const newSet = set1.union(set2)

2023-11-22 02:46 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-30.js
> +const newSet = [...set1, ...set2];
desse jeito não está funcionando, somente do jeito que eu fiz

2023-11-22 13:09 UTC, antoniomatiolijr requested changes

2023-11-22 13:09 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-20.js
> +}
```javascript

const arraysToMap = (keys, values) => {

    if (keys.length !== values.length) {
        throw new Error('Os arrays tem comprimentos diferentes, então não é possível relacioná-los')
    }
    const newMap = new Map()
    let index = 0;
    for (const key of keys) {
        newMap.set(key, values[index]);
        index++;
    }
    return newMap;
}
```

Depois teremos uma aula sobre Erros/Exceções mas testa o código para vc ver como é legal

2023-11-22 13:09 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-30.js
> +const newSet = [...set1, ...set2];
Putz só tem na versão nova

2023-11-22 13:35 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-30.js
> +const newSet = [...set1, ...set2];
ah ta!!

2023-11-22 13:38 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-20.js
> +}
fica bem melhor mesmo, ao invés de devolver a string, devolve o erro

2023-11-22 13:39 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-20.js
> +}
a ordem das coisas tem que ser essa que você mandou?

2023-11-23 12:11 UTC, antoniomatiolijr requested changes

2023-11-23 12:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-20.js
> +    const newMap = new Map();
Faz do jeito que eu falei pq vc não aloca essa variável de forma desnecessária na memória

2023-11-23 12:19 UTC, luanarahal commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-20.js
> +    const newMap = new Map();
Ah entendi!! Primeiro valida se os comprimentos são iguais, se não forem, já sai o erro né, entendi

2023-11-23 14:16 UTC, antoniomatiolijr approved these changes

2023-11-23 14:16 UTC, merged